services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: wkr
      POSTGRES_PASSWORD: wkr
      POSTGRES_DB: wkr
    ports:
      - "127.0.0.1::5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wkr -d wkr"]
      interval: 10s
      timeout: 5s
      retries: 10

  flyway:
    image: flyway/flyway:10
    profiles:
      - migrate
    command: migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/wkr
      FLYWAY_USER: wkr
      FLYWAY_PASSWORD: wkr
      FLYWAY_CONNECT_RETRIES: 60
    volumes:
      - ../db/migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  ml:
    build:
      context: ../ml-service
      dockerfile: Dockerfile
    environment:
      MODEL_PATH: /app/model.json
      MODEL_VERSION: xgb_rul_v3_formula_features
      METRICS_PATH: /app/metrics.json
      RUL_WARN_MINUTES: "120"
      RUL_STOP_MINUTES: "95"
    volumes:
      - ../ml-service/model.json:/app/model.json
      - ../ml-service/metrics.json:/app/metrics.json
    ports:
      - "8001:8001"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  collector:
    build:
      context: ../collector/Collector.Worker
      dockerfile: Dockerfile
    environment:
      BACKEND_BASE_URL: http://backend:8000
      COLLECTOR_MODE: lifecycle

      MACHINE_ID: HAAS_VF2_NGC_01
      TOOL_ID: T12
      TOOL_DIAMETER_MM: "10.0"

      COLLECTOR_PERIOD_MS: "500"

      NORMAL_FRAMES: "70"
      WARNING_FRAMES: "90"
      CRITICAL_FRAMES: "110"

      STOP_AFTER_CRITICAL: "true"
      STOP_FRAMES: "60"
    depends_on:
      db:
        condition: service_healthy
      ml:
        condition: service_healthy
      backend:
        condition: service_started

  backend:
    build:
      context: ../backend/Backend.Api
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8000
      ConnectionStrings__Pg: "Host=db;Port=5432;Database=wkr;Username=wkr;Password=wkr;GSS Encryption Mode=Disable"
      Ml__BaseUrl: http://ml:8001
      Rul__WindowSize: "50"
      Rul__PeriodSeconds: "5"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      ml:
        condition: service_healthy

volumes:
  pgdata: